version: '3'
services:
  db:
    image: postgres
    container_name: "postgres"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
  zookeeper:
    image: zookeeper
    container_name: "zookeeper"
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka
    container_name: "kafka"
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_CREATE_TOPICS: "pingpong:1:1"
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181